# Generated by Django 4.1.2 on 2022-10-13 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Walet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='name')),
                ('type', models.CharField(choices=[('VISA', 'visa card'), ('MASTER_CARD', 'master card card')], default='VISA', max_length=11, verbose_name='type')),
                ('currency', models.CharField(choices=[('USD', 'Dollars'), ('EUR', 'Euro'), ('UAH', 'Hryvnia')], default='USD', max_length=3, verbose_name='currency')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='balance')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='creating_time')),
                ('modefied_on', models.DateTimeField(auto_now=True, verbose_name='modefied_time')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
