# Generated by Django 4.1.2 on 2022-10-18 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='transfer_amount')),
                ('commision', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='commision')),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('FAILED', 'FAILED')], max_length=6, verbose_name='status')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_receiver', to='walletsapi.wallet', verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_sender', to='walletsapi.wallet', verbose_name='sender')),
            ],
        ),
    ]
